server:
  port: 8130 #服务端口

spring:
  profiles:
    active: dev #环境设置
  application:
    name: service-oss #服务名

aliyun:
  oss:
    end-point: oss-cn-beijing.aliyuncs.com
    key-id: LTAI4G5Svnb2TWBMuKnNT6jY
    key-secret: N7v6R4V3EJ1SGDZlsqtqo8QyVVMmtQ
    bucket-name: srb-file-202121