server:
  port: 8120 #服务端口
spring:
  profiles:
    active: dev #环境配置
  application:
    name: service-sms

  #spring
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则一直等待
    lettuce:
      pool:
        max-active: 20 #最大连接数，负值表示没有限制，默认8
        max-wait: -1   #最大阻塞等待时间，负值表示没有限制，默认-1
        max-idle: 8    #最大空闲链接，默认为8
        min-idle: 0    #最小空闲链接，默认为0

#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: LTAI4G5Svnb2TWBMuKnNT6jY
    key-secret: N7v6R4V3EJ1SGDZlsqtqo8QyVVMmtQ
    template-code: SMS_96695065
    sign-name: 谷粒
